### ISSUE TITLE
Airports TODO

### ISSUE THREAD

**Issue by gnomex** [vinicioswentz/crazywork#1]
TODO list for airports list:

- [x] A new list
- [x] Insert node ( push right and left )
- [x] Remove node ( pop right and left )
- [x] Remove a given node (Find and remove from criteria )
- [x] Destroy the list and free memory
- [x] Match nodes function
- [ ] Assign Data (name)
- [ ] Assign flights 
- [x] Iterator Pattern ( Search for name and index )

**Comment by gnomex** [comment]
606f30fb8062818fa8d61009ce4c9201c95be92c
